const USER_LOGIN_REQUEST = 'USER_LOGIN-REQUEST';
const USER_LOGIN_SUCCESS = 'USER_LOGIN-SUCCESS';
const USER_LOGIN_FAIL = 'USER_LOGIN-FAIL';
const USER_LOGOUT = 'USER_LOGOUT';

export { USER_LOGIN_REQUEST, USER_LOGIN_SUCCESS, USER_LOGIN_FAIL, USER_LOGOUT };
