const USER_LOGIN_REQUEST = 'USER_LOGIN-REQUEST';
const USER_LOGIN_SUCCESS = 'USER_LOGIN-SUCCESS';
const USER_LOGIN_FAIL = 'USER_LOGIN-FAIL';
const USER_LOGOUT = 'USER_LOGOUT';
const GET_JOBS_REQUEST = 'GET_JOBS_REQUEST';
const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
const GET_JOBS_FAIL = 'GET_JOBS_FAIL';
const GET_APPLICANTS_REQUEST = 'GET_APPLICANTS_REQUEST';
const GET_APPLICANTS_SUCCESS = 'GET_APPLICANTS_SUCCESS';
const GET_APPLICANTS_FAIL = 'GET_APPLICANTS_FAIL';

export {
  USER_LOGIN_REQUEST,
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAIL,
  USER_LOGOUT,
  GET_JOBS_REQUEST,
  GET_JOBS_SUCCESS,
  GET_JOBS_FAIL,
  GET_APPLICANTS_REQUEST,
  GET_APPLICANTS_SUCCESS,
  GET_APPLICANTS_FAIL,
};
